"""
=============================================================================
LAYER 8: RESPONSE ORCHESTRATION & HARDWARE ACTUATION INTERFACE
Module: executor.py
-----------------------------------------------------------------------------
Problem Solved:
  Executes the optimal incident response action plan generated by Layer 6.
  Grounds abstract mitigation plans in machine-executable control commands
  dispatched across physical and cloud actuation interfaces:
    1. Modbus TCP Register Interface (PLCs, RTUs, SCADA actuators)
    2. OPC-UA Industrial Command Interface (Medical devices, smart sensors)
    3. Network Switch Forwarding-Table Interface (OpenFlow / SDN switches)
    4. Cloud Hypervisor Control-API Interface (AWS/GCP EC2, RDS, IAM)

  Supports both single-action plans and multi-step response strategies
  (e.g. Strategy A: snapshot → block → rotate → notify SOC).
  Solves automated response orchestration with timestamped audit logs.

  Pre-Actuation Certified-Domain Gate:
    The Layer 5 certificate gates SC-IR -> solver compilation. This module closes
    the loop on the far side of the solver: a solver-produced plan is re-validated
    against the certified admissible domain and regenerated budget before any
    actuation command is emitted, so a plan that drifted from the certified
    decision domain cannot reach a physical or cloud interface.

Inputs:  Action plan dictionary {resource_id: action}, optional resource metadata,
         optional certified SC-IR + safety certificate, and optional strategy name.
Outputs: List of timestamped execution log records containing protocol-level
         actuation commands for each mitigation action.
=============================================================================
"""

import datetime
import time
from typing import Dict, List, Optional, Any
from config import RESPONSE_STRATEGIES
from layer5_constraints.constraint_ir import SecurityConstraintIR
from layer5_constraints.safety_certifier import ConstraintSafetyCertificate
from layer5_constraints.formulation_compiler import FormulationCompiler


ACTION_DESCRIPTIONS = {
    "isolate": "Isolating resource from network",
    "rotate_credentials": "Rotating credentials/keys",
    "block_ip": "Blocking associated source IP",
    "disable_user": "Disabling associated user account",
    "snapshot_backup": "Triggering snapshot/backup",
    "monitor": "Monitoring resource",
    "increase_logging": "Increasing logging verbosity",
    "notify_soc": "Notifying SOC team",
    "human_approval": "Waiting for human approval",
}


# Orchestration-only actions that are not part of the optimizer's decision domain
# and therefore carry no certified variable (they emit no device-level command).
NON_DOMAIN_ACTIONS = frozenset({"notify_soc", "human_approval"})


# =============================================================================
# PRE-ACTUATION CERTIFIED-DOMAIN GATE
# =============================================================================

class UncertifiedActuationError(Exception):
    """Raised when actuation is attempted without a valid SC-IR/certificate binding."""


from layer8_orchestration.capability_verifier import (
    ActuationVerificationError,
    ActuationEnvelopeViolationError,
    InadmissibleActionError,
    ActuationBudgetExceededError,
)


def validate_plan_against_certified_ir(
    plan: Dict[str, str],
    sc_ir: SecurityConstraintIR,
    certificate: Optional[ConstraintSafetyCertificate],
    current_snapshot: Optional[Any] = None,
) -> Dict[str, Any]:
    """
    Post-solve, pre-actuation verification gate.

    Re-establishes the cryptographic certificate binding and confirms every action
    in the solver-produced plan lies inside the certified admissible domain and
    within the certified regenerated budget. Also validates against the certified
    validity envelope if current_snapshot is provided. Raises on any violation.
    """
    if sc_ir is None:
        raise UncertifiedActuationError(
            "Actuation rejected: no SecurityConstraintIR supplied for plan validation."
        )

    # Reuse the canonical Layer 5 binding verifier (status, versions, digests, envelope).
    FormulationCompiler.verify_binding(sc_ir, certificate, current_snapshot=current_snapshot)

    validated: Dict[str, str] = {}
    for rid, action in plan.items():
        if action in NON_DOMAIN_ACTIONS:
            continue

        domain = sc_ir.variable_domains.get(rid)
        if domain is None:
            raise InadmissibleActionError(
                f"Actuation rejected: resource '{rid}' has no certified variable domain in the SC-IR."
            )
        if action not in domain.admissible_actions:
            raise InadmissibleActionError(
                f"Actuation rejected: action '{action}' on '{rid}' is outside the certified "
                f"admissible domain {sorted(domain.admissible_actions)}. "
                f"Pruned actions for this resource: {sorted(domain.pruned_actions)}."
            )
        validated[rid] = action

    total_cost = 0.0
    if sc_ir.budget_constraint:
        cost_map = sc_ir.budget_constraint.cost_map or {}
        total_cost = sum(cost_map.get((rid, act), 0.0) for rid, act in validated.items())
        if total_cost > sc_ir.budget_constraint.max_budget:
            raise ActuationBudgetExceededError(
                f"Actuation rejected: plan cost {total_cost:.4f} exceeds certified "
                f"regenerated budget {sc_ir.budget_constraint.max_budget:.4f}."
            )

    return {
        "validated_actions": len(validated),
        "skipped_non_domain_actions": len(plan) - len(validated),
        "total_plan_cost": round(total_cost, 4),
        "certified_budget": sc_ir.budget_constraint.max_budget if sc_ir.budget_constraint else None,
        "certificate_id": certificate.certificate_id if certificate else None,
        "ir_digest": sc_ir.compute_canonical_digest(),
    }


# =============================================================================
# HARDWARE & CLOUD ACTUATION INTERFACES (Patent Claim 1 Actuation Grounding)
# -----------------------------------------------------------------------------
# SCOPE: these classes are protocol-specific COMMAND BUILDERS. They construct the
# control payload each interface would carry and return it for audit; they open no
# socket, establish no session, and perform no device authentication. Every record
# is therefore reported with status "simulated_success".
#
# Register addresses, node identifiers and match fields below are REPRESENTATIVE
# vendor mappings, not protocol-mandated constants: Modbus defines function codes
# (0x03/0x06/0x10) but assigns no meaning to specific holding registers, and OPC-UA
# node identifiers are server-defined. A live deployment binds these to a device
# profile. Substituting a real adapter means implementing dispatch() against the
# corresponding client library while preserving these return keys.
# =============================================================================

class ModbusActuator:
    """
    Modbus TCP Industrial Actuator Interface.
    Dispatches holding register writes and coils to Programmable Logic
    Controllers (PLCs) and remote terminal units (RTUs) over Modbus TCP (port 502).
    """
    PROTOCOL = "MODBUS_TCP"
    INTERFACE_TYPE = "INDUSTRIAL_PLC_REGISTER"

    @classmethod
    def dispatch(cls, resource_id: str, action: str) -> Dict[str, Any]:
        unit_id = (abs(hash(resource_id)) % 247) + 1
        if action == "rotate_credentials":
            # Function Code 0x10: Write Multiple Holding Registers (Security Key Buffer)
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "function_code": "0x10 (Write Multiple Registers)",
                "unit_id": unit_id,
                "register_address": 40200,
                "quantity": 4,
                "payload_hex": "A1B2C3D4E5F60718",
                "action_effect": "Re-keyed symmetric authentication credentials on PLC controller",
            }
        elif action in ("increase_logging", "monitor"):
            # Function Code 0x06: Write Single Holding Register (Diagnostics Mode)
            val = 0x0003 if action == "increase_logging" else 0x0001
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "function_code": "0x06 (Write Single Register)",
                "unit_id": unit_id,
                "register_address": 40105,
                "value": val,
                "action_effect": f"Set PLC diagnostic telemetry verbosity to {val}",
            }
        elif action == "isolate":
            # Hardware safety interlock: automated network disconnection barred on physical PLCs
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "function_code": "0x06 (Write Single Register)",
                "unit_id": unit_id,
                "register_address": 40999,
                "value": 0xFFFF,
                "action_effect": "SAFETY INTERLOCK: Physical relay disconnect blocked; switched to safe standby mode",
            }
        else:
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "function_code": "0x03 (Read Holding Registers)",
                "unit_id": unit_id,
                "register_address": 40001,
                "quantity": 2,
                "action_effect": f"Executed baseline command '{action}' via Modbus TCP",
            }


class OpcUaActuator:
    """
    OPC-UA Industrial Actuator Interface (IEC 62541).
    Dispatches structured industrial service method calls to SCADA servers,
    medical devices, and industrial IoT camera sensors.
    """
    PROTOCOL = "OPC_UA"
    INTERFACE_TYPE = "INDUSTRIAL_OPC_UA_SERVER"

    @classmethod
    def dispatch(cls, resource_id: str, action: str) -> Dict[str, Any]:
        node_ns = f"ns=2;s={resource_id}"
        if action == "rotate_credentials":
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "node_id": f"{node_ns}/SecurityManager",
                "method": "RotateX509Certificate",
                "arguments": {"key_length": 4096, "revocation_check": True},
                "action_effect": "Issued OPC-UA X.509 certificate renewal to cyber-physical node",
            }
        elif action == "block_ip":
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "node_id": f"{node_ns}/FirewallSubsystem",
                "method": "BlockIngressEndpoint",
                "arguments": {"filter_rule": "DROP_SUSPECT_ORIGIN"},
                "action_effect": "Injected hardware firewall ingress drop rule on smart sensor",
            }
        elif action == "increase_logging":
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "node_id": f"{node_ns}/AuditService",
                "method": "ConfigureLoggingProfile",
                "arguments": {"level": "DIAGNOSTIC_TRACE", "publish_rate_ms": 100},
                "action_effect": "Increased OPC-UA diagnostic trace sample rate",
            }
        else:
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "node_id": f"{node_ns}/TelemetryNode",
                "method": "QueryOperationalState",
                "arguments": {"action": action},
                "action_effect": f"Dispatched OPC-UA action '{action}'",
            }


class NetworkSwitchActuator:
    """
    Network Switch Forwarding-Table Actuator Interface (OpenFlow / SDN).
    Dispatches OpenFlow v1.3/v1.5 flow-mod messages to physical and virtual
    network switches, gateways, and routers.
    """
    PROTOCOL = "OPENFLOW_SDN"
    INTERFACE_TYPE = "NETWORK_SWITCH_FORWARDING_TABLE"

    @classmethod
    def dispatch(cls, resource_id: str, action: str) -> Dict[str, Any]:
        if action == "isolate":
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "flow_mod_command": "OFPFC_ADD",
                "table_id": 0,
                "priority": 50000,
                # OXM metadata is a 64-bit masked field, so the resource identifier is
                # carried as an annotation rather than stuffed into the match.
                "match": {"in_port": 1},
                "target_resource": resource_id,
                "instructions": [{"type": "OFPIT_APPLY_ACTIONS", "actions": [{"type": "OFPAT_DROP"}]}],
                "action_effect": f"Flow-mod rule injected: Complete network isolation (DROP) for {resource_id}",
            }
        elif action == "block_ip":
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "flow_mod_command": "OFPFC_ADD",
                "table_id": 0,
                "priority": 40000,
                "match": {"eth_type": "0x0800", "ipv4_src": "198.51.100.0/24"},
                "instructions": [{"type": "OFPIT_APPLY_ACTIONS", "actions": [{"type": "OFPAT_DROP"}]}],
                "action_effect": f"Flow-mod rule injected: Ingress IP drop rule on switch port for {resource_id}",
            }
        elif action == "increase_logging":
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "flow_mod_command": "OFPFC_MODIFY",
                "table_id": 0,
                "priority": 30000,
                "match": {"in_port": 1},
                "instructions": [{"type": "OFPIT_APPLY_ACTIONS", "actions": [{"type": "OFPAT_OUTPUT", "port": "OFPP_CONTROLLER"}]}],
                "action_effect": f"Mirrored data-plane packet stream to SIEM/SOC capture interface",
            }
        else:
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "flow_mod_command": "OFPFC_MODIFY",
                "table_id": 0,
                "priority": 10000,
                "match": {"in_port": 1},
                "instructions": [{"type": "OFPIT_APPLY_ACTIONS", "actions": [{"type": "OFPAT_NORMAL"}]}],
                "action_effect": f"Preserved baseline switch forwarding policy for {resource_id}",
            }


class CloudHypervisorActuator:
    """
    Cloud Hypervisor API Actuator Interface.
    Dispatches authenticated control-plane API calls to cloud hypervisors and
    infrastructure platforms (AWS EC2/RDS/IAM, GCP Compute/CloudSQL).
    """
    PROTOCOL = "CLOUD_HYPERVISOR_API"
    INTERFACE_TYPE = "CLOUD_CONTROL_PLANE_API"

    @classmethod
    def dispatch(cls, resource_id: str, action: str) -> Dict[str, Any]:
        if action == "isolate":
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "service": "ec2",
                "api_call": "ModifyInstanceAttribute",
                "parameters": {"InstanceId": resource_id, "Groups": ["sg-quarantine-isolated"]},
                "action_effect": f"Detached standard security groups and attached quarantine security group",
            }
        elif action == "rotate_credentials":
            # IAM key rotation is a sequence, not a single call: the new key must exist
            # and be distributed before the compromised key is deactivated. UpdateAccessKey
            # additionally requires AccessKeyId - UserName alone is not a valid request.
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "service": "iam",
                "api_call": "CreateAccessKey -> UpdateAccessKey",
                "call_sequence": [
                    {"api_call": "ListAccessKeys", "parameters": {"UserName": resource_id}},
                    {"api_call": "CreateAccessKey", "parameters": {"UserName": resource_id}},
                    {
                        "api_call": "UpdateAccessKey",
                        "parameters": {
                            "UserName": resource_id,
                            "AccessKeyId": "<compromised-key-id from ListAccessKeys>",
                            "Status": "Inactive",
                        },
                    },
                ],
                "action_effect": "Issued replacement IAM access key, then deactivated the compromised key",
            }
        elif action == "snapshot_backup":
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "service": "rds",
                "api_call": "CreateDBSnapshot",
                "parameters": {"DBInstanceIdentifier": resource_id, "DBSnapshotIdentifier": f"snap-{resource_id}-{int(time.time())}"},
                "action_effect": f"Triggered point-in-time snapshot to immutable backup storage",
            }
        elif action == "disable_user":
            # PasswordResetRequired only forces a change at NEXT sign-in; it does not
            # terminate sessions already in flight. Revoking those requires a deny policy
            # conditioned on aws:TokenIssueTime (the AWSRevokeOlderSessions pattern).
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "service": "iam",
                "api_call": "PutUserPolicy + UpdateLoginProfile",
                "call_sequence": [
                    {
                        "api_call": "PutUserPolicy",
                        "parameters": {
                            "UserName": resource_id,
                            "PolicyName": "AWSRevokeOlderSessions",
                            "PolicyDocument": {
                                "Effect": "Deny",
                                "Action": "*",
                                "Resource": "*",
                                "Condition": {"DateLessThan": {"aws:TokenIssueTime": "<revocation-timestamp>"}},
                            },
                        },
                    },
                    {
                        "api_call": "UpdateLoginProfile",
                        "parameters": {"UserName": resource_id, "PasswordResetRequired": True},
                    },
                ],
                "action_effect": "Denied credentials issued before revocation time, then forced password reset",
            }
        else:
            return {
                "protocol": cls.PROTOCOL,
                "interface": cls.INTERFACE_TYPE,
                "service": "cloudwatch",
                "api_call": "PutMetricAlarm",
                "parameters": {"Resource": resource_id, "MonitoringLevel": "Detailed"},
                "action_effect": f"Configured heightened telemetry alarms for {resource_id}",
            }


def _infer_resource_type(resource_id: str, metadata: Optional[Dict[str, Any]] = None) -> str:
    """Infers or retrieves the canonical asset type for actuation routing."""
    if metadata and "type" in metadata:
        return metadata["type"]
    rid_lower = resource_id.lower()
    if "plc" in rid_lower:
        return "plc_controller"
    if "med" in rid_lower or "medical" in rid_lower:
        return "medical_device"
    if "camera" in rid_lower or "sensor" in rid_lower:
        return "camera_sensor"
    if "router" in rid_lower or "gateway" in rid_lower or "switch" in rid_lower or "gw" in rid_lower:
        return "network_gateway"
    if "db" in rid_lower or "rds" in rid_lower or "sql" in rid_lower:
        return "rds_database"
    if "iam" in rid_lower or "role" in rid_lower or "user" in rid_lower:
        return "iam_role"
    return "ec2_instance"


def _execute_action(
    resource_id: str,
    action: str,
    step: Optional[int] = None,
    resource_meta: Optional[Dict[str, Any]] = None,
    expected_state_revision: Optional[int] = None,
) -> dict:
    """
    Executes an action by dispatching machine-level control commands to the
    appropriate physical or cloud interface.
    """
    timestamp = datetime.datetime.now().isoformat(timespec="seconds")
    step_str = f" (Step {step})" if step is not None else ""
    description = ACTION_DESCRIPTIONS.get(action, f"Executing {action}")

    rtype = _infer_resource_type(resource_id, resource_meta)

    # Route to appropriate actuation driver based on cyber-physical taxonomy
    if rtype == "plc_controller":
        actuator_record = ModbusActuator.dispatch(resource_id, action)
    elif rtype in ("medical_device", "camera_sensor"):
        actuator_record = OpcUaActuator.dispatch(resource_id, action)
    elif rtype in ("network_gateway", "vpc_router", "load_balancer"):
        actuator_record = NetworkSwitchActuator.dispatch(resource_id, action)
    else:
        actuator_record = CloudHypervisorActuator.dispatch(resource_id, action)

    if "command" in actuator_record and isinstance(actuator_record["command"], dict):
        actuator_record["command"]["expected_state_revision"] = expected_state_revision
    actuator_record["expected_state_revision"] = expected_state_revision

    log_line = (
        f"[{timestamp}] {resource_id}{step_str}: {description} "
        f"[Interface: {actuator_record['interface']} | Protocol: {actuator_record['protocol']}]"
    )
    print(log_line)

    return {
        "resource_id": resource_id,
        "action": action,
        "step": step,
        "timestamp": timestamp,
        "status": "simulated_success",  # Preserves exact backward-compatible verification assertion
        "protocol": actuator_record["protocol"],
        "interface_type": actuator_record["interface"],
        "actuation_command": actuator_record,
        "resource_type": rtype,
        "expected_state_revision": expected_state_revision,
    }


class SimulatedDeviceInterface:
    """
    Simulated Device-Side Control Interface.
    Maintains a simulated local hardware/device state revision (state epoch).
    Enforces that incoming actuation commands carry an expected_state_revision
    matching the current device revision. If revisions differ (e.g. TOCTOU race),
    the command is rejected.
    """
    def __init__(self, device_id: str, initial_revision: int = 1):
        self.device_id = device_id
        self.current_revision = initial_revision

    def bump_revision(self, delta: int = 1) -> int:
        """Simulates an asynchronous physical state mutation on the device."""
        self.current_revision += delta
        return self.current_revision

    def execute_command(self, command_record: Dict[str, Any]) -> Dict[str, Any]:
        """
        Receives and executes an actuation command. Rejects if expected revision != current.
        """
        expected_rev = command_record.get("expected_state_revision")
        if expected_rev is None:
            return {
                "status": "rejected",
                "error": "Missing expected_state_revision in actuation command",
                "device_id": self.device_id,
                "current_revision": self.current_revision,
            }
        if expected_rev != self.current_revision:
            return {
                "status": "rejected",
                "error": f"Device state revision race detected: command expected revision {expected_rev} != device current revision {self.current_revision}",
                "device_id": self.device_id,
                "expected_revision": expected_rev,
                "current_revision": self.current_revision,
            }
        return {
            "status": "simulated_success",
            "device_id": self.device_id,
            "revision": self.current_revision,
            "executed_command": command_record,
        }


def execute_plan(
    plan: dict,
    resource_metadata: Optional[Dict[str, Dict[str, Any]]] = None,
    sc_ir: Optional[SecurityConstraintIR] = None,
    certificate: Optional[ConstraintSafetyCertificate] = None,
    current_snapshot: Optional[Any] = None,
    public_key: Optional[Any] = None,
) -> list:
    """
    plan: {resource_id: action}
    resource_metadata: optional {resource_id: {type: ...}}
    sc_ir / certificate: when supplied, the plan is validated against the certified
        admissible domain, budget, and validity envelope before any actuation command is emitted.
    current_snapshot: optional StateSnapshot to enforce validity envelope at actuation boundary.
    Returns list of execution log records with protocol-level actuation commands.
    """
    meta_map = resource_metadata or {}
    domain_certified = False
    envelope_valid = False
    epoch_valid = False
    expected_rev = None

    if certificate is not None:
        from layer8_orchestration.capability_verifier import ActuationCapabilityVerifier
        auth = ActuationCapabilityVerifier.authorize(
            plan=plan,
            certificate=certificate,
            current_snapshot=current_snapshot,
            public_key=public_key,
        )
        domain_certified = auth.domain_certified
        envelope_valid = auth.envelope_valid
        epoch_valid = auth.epoch_valid
        expected_rev = auth.expected_state_revision
    elif sc_ir is not None:
        validate_plan_against_certified_ir(plan, sc_ir, certificate, current_snapshot=current_snapshot)
        domain_certified = True
        envelope_valid = True
        epoch_valid = True
        expected_rev = getattr(current_snapshot, "epoch", getattr(sc_ir, "state_epoch", 1))
    elif current_snapshot is not None:
        expected_rev = getattr(current_snapshot, "epoch", 1)

    logs = [
        _execute_action(rid, action, resource_meta=meta_map.get(rid), expected_state_revision=expected_rev)
        for rid, action in plan.items()
    ]
    for log in logs:
        log["domain_certified"] = domain_certified
        log["envelope_valid"] = envelope_valid
        log["epoch_valid"] = epoch_valid
        log["expected_state_revision"] = expected_rev
    return logs


def execute_strategy(
    strategy_name: str,
    plan: dict,
    step_delay: float = 0.5,
    resource_metadata: Optional[Dict[str, Dict[str, Any]]] = None,
    sc_ir: Optional[SecurityConstraintIR] = None,
    certificate: Optional[ConstraintSafetyCertificate] = None,
    current_snapshot: Optional[Any] = None,
    public_key: Optional[Any] = None,
) -> list:
    """
    Executes a multi-step response strategy across physical and cloud actuation interfaces.
    When sc_ir is supplied, every (resource, action) the strategy would apply is validated
    against the certified admissible domain and validity envelope first.
    Returns a list of all log records from all steps.
    """
    all_logs = []
    strategy = RESPONSE_STRATEGIES.get(strategy_name, [])
    meta_map = resource_metadata or {}
    certified = sc_ir is not None
    step_num = 1

    for action in strategy:
        if certified:
            validate_plan_against_certified_ir(
                {rid: action for rid in plan}, sc_ir, certificate, current_snapshot=current_snapshot
            )
        for resource_id in plan:
            log = _execute_action(resource_id, action, step_num, resource_meta=meta_map.get(resource_id))
            log["domain_certified"] = certified
            all_logs.append(log)
        step_num += 1
        time.sleep(step_delay)

    return all_logs


if __name__ == "__main__":
    print("=== Layer 8: Testing single-action plan with hardware & cloud actuators ===")
    demo_plan = {
        "plc_turbine_01": "rotate_credentials",
        "med_pump_02": "increase_logging",
        "gw_perimeter_03": "isolate",
        "ec2_app_server_04": "isolate",
    }
    demo_meta = {
        "plc_turbine_01": {"type": "plc_controller"},
        "med_pump_02": {"type": "medical_device"},
        "gw_perimeter_03": {"type": "network_gateway"},
        "ec2_app_server_04": {"type": "ec2_instance"},
    }
    logs1 = execute_plan(demo_plan, resource_metadata=demo_meta)
    for log in logs1:
        print(f"  -> {log['resource_id']}: Protocol={log['protocol']} | Interface={log['interface_type']}")
