"""
=============================================================================
LAYER 8: RESPONSE ORCHESTRATION & EXECUTION
Module: executor.py
-----------------------------------------------------------------------------
Problem Solved:
  Executes the optimal incident response action plan generated by Layer 6.
  Supports both single-action plans and multi-step response strategies
  (e.g. Strategy A: snapshot → block → rotate → notify SOC).
  Solves automated response orchestration with timestamped audit logs.

Inputs:  Action plan dictionary {resource_id: action} and optional strategy name.
Outputs: List of timestamped execution log records for each mitigation action.
=============================================================================
"""

import datetime
import time
from config import RESPONSE_STRATEGIES


ACTION_DESCRIPTIONS = {
    "isolate": "Isolating resource from network (simulated)",
    "rotate_credentials": "Rotating credentials/keys (simulated)",
    "block_ip": "Blocking associated source IP (simulated)",
    "disable_user": "Disabling associated user account (simulated)",
    "snapshot_backup": "Triggering snapshot/backup (simulated)",
    "monitor": "Monitoring resource (simulated)",
    "increase_logging": "Increasing logging verbosity (simulated)",
    "notify_soc": "Notifying SOC team (simulated)",
    "human_approval": "Waiting for human approval (simulated)",
}


def _execute_action(resource_id: str, action: str, step: int = None) -> dict:
    timestamp = datetime.datetime.now().isoformat(timespec="seconds")
    step_str = f" (Step {step})" if step is not None else ""
    description = ACTION_DESCRIPTIONS.get(action, f"Executing {action}")
    log_line = f"[{timestamp}] {resource_id}{step_str}: {description}"
    print(log_line)
    return {
        "resource_id": resource_id,
        "action": action,
        "step": step,
        "timestamp": timestamp,
        "status": "simulated_success"
    }


def execute_plan(plan: dict) -> list:
    """plan: {resource_id: action} -> returns list of execution log records"""
    return [_execute_action(rid, action) for rid, action in plan.items()]


def execute_strategy(
    strategy_name: str,
    plan: dict,
    step_delay: float = 0.5
) -> list:
    """
    Executes a multi-step response strategy.
    Returns a list of all log records from all steps.
    """
    all_logs = []
    strategy = RESPONSE_STRATEGIES.get(strategy_name, [])
    step_num = 1

    for action in strategy:
        for resource_id in plan:
            log = _execute_action(resource_id, action, step_num)
            all_logs.append(log)
        step_num += 1
        time.sleep(step_delay)

    return all_logs


if __name__ == "__main__":
    print("=== Layer 8: Testing single-action plan ===")
    demo_plan = {"vm-1": "isolate", "iam-role-2": "rotate_credentials"}
    logs1 = execute_plan(demo_plan)

    print("\n=== Layer 8: Testing multi-step strategy (Strategy A) ===")
    logs2 = execute_strategy("Strategy A", demo_plan)
